project:
  title: "Measles"
  type: book
  output-dir: docs
  
execute:
  freeze: auto

book:
  title: "Đánh giá hệ số lây nhiễm theo thời gian thực của Sởi"
  author: HCDC - OUCRU
  date: "09/29/2024"
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - rt_2024.qmd
    - qhncc.qmd
    - qhnct.qmd
    - nx.qmd
    - rt_2019.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    echo: false
    embed-resources: true
    theme: [cosmo, custom.scss]
    code-overflow: wrap
    fig-format: svg
    df-print: paged
    toc: true
    toc-title: "Mục lục"
    toc-depth: 5
    toc-expand: 3
    message: false
    warning: false